from . import legal_case_folder
from . import pv
from . import expense_charge 
from . import payment
from . import trial
from . import document
from . import tribunal
from . import tribunal_type 
from . import legal_case_type 
from . import res_partner 
